---
defaults: &defaults
  docker:
    - image: greenpeaceinternational/circleci-base:latest

version: 2

jobs:
  lint:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir /tmp/artifacts
      - run: make lint
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Test" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/lint.log)\`\`\`" \
            notify-job-failure.sh

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: mkdir /tmp/artifacts
      - run: activate-gcloud-account.sh
      - run: make
      - run: cp -R ingress /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Notify failure
          when: on_fail
          command: |
            TYPE="Test" \
            EXTRA_TEXT="\`\`\`$(cat /tmp/lint.log)\`\`\`" \
            notify-job-failure.sh

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - deploy:
          context: org-global
          requires:
            - lint
          filters:
            branches:
              only:
                - master
